### ISSUE TITLE
Alternative Download Source

### ISSUE THREAD

**Issue by IzzySoft** [ELTEGANI/ExpenseMonitorApp#98]
Would you mind attaching the APK to its corresponding [release](https://github.com/ELTEGANI/ExpenseMonitorApp/releases) – so users without Play Store (like those on Huawei devices) get a chance to use it? Thanks in advance!

**Comment by ELTEGANI** [comment]
@IzzySoft okay, I will attach it.

**Comment by IzzySoft** [comment]
Thanks a lot – also in the name of all affected :smiley: Once it's attached, if you then close this issue I'll get a notification to pick it up.

**Comment by IzzySoft** [comment]
@ELTEGANI may I ask for an ETA? It's 2 months now :pray:

**Comment by ELTEGANI** [comment]
> @ELTEGANI may I ask for an ETA? It's 2 months now

Sir @IzzySoft sorry for that, during this month I will attach it. Thanks :)

**Comment by IzzySoft** [comment]
Thanks! Yeah, at times Real Life intervenes with such profan tasks :laughing:

**Comment by IzzySoft** [comment]
Hope you don't mind my nagging again. I don't know by which calendar you go and what day your month ends – but according to one, it ended yesterday, and according to the other two known to me a week earlier… So from the first one, I wish you a happy new year :smile:

**Comment by ELTEGANI** [comment]
Sir @IzzySoft please accept my apology I didn't mean to totally ignore you in that way thanks for your patent and happy new year wish you all the best :). I attached an updated APK.

[expensemonitor.zip](https://github.com/ELTEGANI/ExpenseMonitorApp/files/5759746/expensemonitor.zip)

**Comment by IzzySoft** [comment]
Thanks a lot – and it wasn't my intention to "blame" :smiley: As for the APK, I was rather asking to attach it to its corresponding [release](https://github.com/ELTEGANI/ExpenseMonitorApp/releases), so users can find it easily (as that's the most common place to look for it) – and for continuing that with future versions. A ZIP in an issue would rather be missed… But seeing now the app depends on GMS & Firebase, initially mentioned Huawei users won't be able to use it.

**Comment by ELTEGANI** [comment]
> Thanks a lot – and it wasn't my intention to "blame"  As for the APK, I was rather asking to attach it to its corresponding [release](https://github.com/ELTEGANI/ExpenseMonitorApp/releases), so users can find it easily (as that's the most common place to look for it) – and for continuing that with future versions. A ZIP in an issue would rather be missed… But seeing now the app depends on GMS & Firebase, initially mentioned Huawei users won't be able to use it.

**Comment by ELTEGANI** [comment]
> Thanks a lot – and it wasn't my intention to "blame"  As for the APK, I was rather asking to attach it to its corresponding [release](https://github.com/ELTEGANI/ExpenseMonitorApp/releases), so users can find it easily (as that's the most common place to look for it) – and for continuing that with future versions. A ZIP in an issue would rather be missed… But seeing now the app depends on GMS & Firebase, initially mentioned Huawei users won't be able to use it.

Sir @IzzySoft I did what you suggest. users can use it just won't receive updates

**Comment by IzzySoft** [comment]
Thanks! Users picking it from there are aware of that.

If GMS & Firebase wouldn't be involved, I could offer picking it from there automatically and provide it via [my repo](https://apt.izzysoft.de/fdroid) – so users could receive automated updates within 24h of your releasing them. But "sensitive information" combined with "possible data leaks" (those two are proprietary components, so it's impossible to tell what they might leak to Google; being part of the app itself they have access to all its data and the developer has no real control on them) is a blocker for that.

Maybe it's possible to have a build flavor not requiring those?

**Comment by ELTEGANI** [comment]
> Thanks! Users picking it from there are aware of that.
> 
> If GMS & Firebase wouldn't be involved, I could offer picking it from there automatically and provide it via [my repo](https://apt.izzysoft.de/fdroid) – so users could receive automated updates within 24h of your releasing them. But "sensitive information" combined with "possible data leaks" (those two are proprietary components, so it's impossible to tell what they might leak to Google; being part of the app itself they have access to all its data and the developer has no real control on them) is a blocker for that.
> 
> Maybe it's possible to have a build flavor not requiring those?

let users pick it up from your repo no GMS & Firebase invloved

**Comment by IzzySoft** [comment]
> let users pick it up from your repo no GMS & Firebase invloved

Sure? My library scanner tells me something different:

```
Libraries detected:
-------------------
* Android Support v4 (/android/support/v4): Development Framework
* Arch (/androidx/arch): Utility
* AppCompat (/androidx/appcompat): Utility
* Constraint Layout Library (/androidx/constraintlayout): Utility
* Androidx Core (/androidx/core): Utility
* Documentfile (/androidx/documentfile): UI Component
* Exifinterface (/androidx/exifinterface): Utility
* androidx.legacy (/androidx/legacy): Utility
* Lifecycle (/androidx/lifecycle): Utility
* Loader (/androidx/loader): Utility
* Media (/androidx/media): Utility
* Navigation (/androidx/navigation): Utility
* Preference (/androidx/preference): Utility
* Print (/androidx/print): Utility
* Room (/androidx/room): Utility
* Sqlite (/androidx/sqlite): Utility
* AndroidX Test (/androidx/test): Development Framework
* Transition (/androidx/transition): UI Component
* Vectordrawable (/androidx/vectordrawable): UI Component
* Glide (/com/bumptech/glide): Utility
* MPAndroidChart (/com/github/mikephil/charting): Utility
* Google Mobile Services (/com/google/android/gms): Development Framework NonFreeDep
* Google Material Design (/com/google/android/material): Utility
* Google Play Core (/com/google/android/play/core): Utility NonFreeNet
* Firebase (/com/google/firebase): Utility NonFreeNet
* Kotlin Coroutine Adapter (/com/jakewharton/retrofit2): Utility
* ThreeTen Android Backport (/com/jakewharton/threetenabp): Utility
* Moshi JSON library (/com/squareup/moshi): Utility
* SearchableSpinner (/com/toptoche/searchablespinnerlibrary): UI Component
* Dagger (/dagger): Utility
* JavaX Annotation API (/javax/annotation): Utility
* JavaX Dependency Injection (/javax/inject): Utility
* Kotlin (/kotlin): Utility
* kotlinx.coroutines (/kotlinx/coroutines): Utility
* OkHttp okio Framework (/okio): Utility
* IntelliJ IDEA (/org/intellij): Utility
* ThreeTen backport project (/org/threeten/bp): Utility
* Retrofit (/retrofit2): Utility

Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Google Play Core (/com/google/android/play/core): NonFreeNet
* Firebase (/com/google/firebase): NonFreeNet
```

(`NonFreeDep` means a dependency on a non-free/proprietary library, `NonFreeNet` means usage of a non-free network service; GMS also means that GApps must be present on the device, which is not met by e.g. recent Huawei devices)

Apart from that, my updater can only deal with `*.apk`, not with `*.zip`.

**Comment by ELTEGANI** [comment]
I used core lib to send updates via google paly

**Comment by IzzySoft** [comment]
So it's not needed for core functionality? Then maybe establishing a "foss build flavor" would be acceptable for you? I'm no Android dev myself, but if you'd need help with that I might know someone to ask to provide that via a pull request. Then you could deploy the usual "full version" to play, and attach a "foss version" to your releases here (or we could even see to bring it to F-Droid then, so you'd only need to tag and had not to "fiddle" with attaching the APK).
